moevm/document_insight_system

- app/servants/pre_luncher.py
- app/server.py
- app/settings.py
- assets/scripts/main.js
- package.json
> Add admin for deploy

- app/bd_helper/bd_types.py
- app/bd_helper/clear_users.py
- app/main/checker.py
- app/main/parser.py
- app/nlp/find_tasks_on_slides.py
- app/nlp/similarity_of_texts.py
- app/servants/data.py
- app/servants/pre_luncher.py
- app/servants/user.py
- app/server.py
- docker-compose.yml
> Change logs

- app/server.py
- app/settings.py
- app/utils/decorators.py
- docker-compose-dev.yml
- templates/login.html
> Signup page flag / iss98

- app/bd_helper/bd_types.py
- app/main/checker.py
- app/nlp/similarity_of_texts.py
- app/nlp/stemming.py
- assets/scripts/criteria.js
- db_versioning/db_versioning.py
- db_versioning/versions.py
- templates/criteria.html
- templates/results.html
> New DB approach and version

- templates/check_list.html
> word break in checklist

- app/main/checker.py
- app/main/checks/further_dev.py
- app/main/checks/sld_enum.py
- app/main/checks/sld_num.py
- app/main/checks/sld_similarity.py
- app/main/checks/title_format.py
- app/nlp/similarity_of_texts.py
- app/nlp/stemming.py
- app/utils/parse_for_html.py
- dependencies.txt
- templates/results.html
mainly affecting results.html, minor ch in verdicts, stemming.py & similarity of slides
> Dynamical results.html

- app/server.py
- app/utils/checklist_filter.py
- assets/scripts/check_list.js
- dependencies.txt
- templates/check_list.html
- templates/upload.html
> checklist export

- app/bd_helper/bd_helper.py
- app/bd_helper/bd_types.py
- app/main/checker.py
- app/server.py
- assets/scripts/check_list.js
- templates/check_list.html
> checklist modifications

- app/bd_helper/bd_helper.py
- app/server.py
> Latest check route

- app/server.py
- templates/upload_textfile.html
Демо страницы для загрузки текстовых файлов. Страница загрузки расположена по пути `/textfiles/upload`.
> Add web page for loading text files

- app/db/db_methods.py
- app/db/db_types.py
- app/main/checker.py
- app/passback_grades.py
- app/server.py
- app/tasks.py
- app/templates/check_list.html
- app/templates/results.html
- app/utils/__init__.py
- app/utils/formatters.py
close #374
close #375
close #376 
close #377
close #378
> Check pipeline / tables / export fixes

- assets/scripts/upload.js
Кастомизация сообщения об ошибке, когда загружаемый материал больше чем максимально разрешенный объем (Issue #430 и #435)
> 430 and 435 info max value

- app/templates/results.html
- assets/styles/results.css
Add links to check_list.html from results.html
> 437 links for results html

- app/main/check_packs/pack_config.py
- app/main/checks/__init__.py
- app/main/checks/report_checks/__init__.py
- app/main/checks/report_checks/spelling_check.py
- requirements.txt
Реализована проверка орфографии у отчетов ВКР на базе средства LanguageTool.
> Spelling check criteria for reports

- app/main/check_packs/pack_config.py
- app/main/checks/__init__.py
- app/main/checks/presentation_checks/__init__.py
- app/main/checks/presentation_checks/empty_slide_check.py
- app/main/parser.py
- app/main/presentations/pptx/slide_pptx.py
- app/main/presentations/slide_basic.py
Добавлен критерий проверки пустых слайдов в презентации. Файл "empty_slide_check"
> add empty_slide_check

- .github/workflows/label_merge_conflicts.yml
Добавлена проверка конфликтов при слиянии с базоывами настройками:
(количество перепроверок: 5
интервал между попытками: 5000 мс)
> 472 auto label merge conflicts

- app/main/checks/report_checks/literature_references.py
Добавлен кретерий-параметр количества литературы (минимальный и максимальный)
Реализуется после проверки существующего источника на другие ошибки.
> add min and max border lit_references

- app/nlp/stemming.py
- app/tasks.py
- app/templates/criteria_pack.html
- assets/scripts/main.js
- package.json
- изменение библиотеки для получения хэша пароля при авторизации (на `crypto-js` жалуется `Dependabot alerts` + нам не нужна столь мощная либа для простого md5)
- скачивание файлов для nltk и language_tool_python перенесено на момент запуска celery worker (ранее загружалось и в web, и в worker + во время работы критериев)
> Project updates

- app/templates/upload.html
- assets/scripts/upload.js
Исправлен баг с кнопкой загрузки
задача:
https://github.com/moevm/document_insight_system/issues/520
> fix button upload

- app/server.py
- app/templates/intro_page.html
- app/templates/login.html
Изменения согласно задаче
https://github.com/moevm/document_insight_system/issues/513
(добавлена информация по "правильному" входу в систему для пользователей
Добавлена приветственная страница
Изменен route('/'))
> 513 message for wrong login

- app/db/db_methods.py
- app/templates/admin_criterions.html
- app/templates/login.html
- assets/scripts/admin_criterions.js
- assets/scripts/main.js
- assets/styles/admin_criterions.css
Исправлен баг с хаотично открывающимися рядами в таблице (при использовании кнопки для открытия всех скрытых рядов),
Улучшен вид кнопки для открытия всех скрытых рядов разом.
> bugs with hidden raw is fixed, showallverdicts button is improved

- app/db/db_methods.py
- app/routes/users.py
- app/server.py
- app/templates/one_user_info.html
- app/templates/user_list.html
- assets/scripts/main.js
- assets/scripts/one_user_info.js
- assets/scripts/user_list.js
Добавлены варианты страницы "/users" и "users/<username>".
Страницы содержат bootstrap-таблицы c фильтрацией по необходимым критериям.
Сейчас таблица со страницы пользователя создана как шаблон и фактически дублирует основную таблицу, необходимы дополнительные пояснения, как ее изменить (или же удалить вовсе).
> 506 bluprint users

- .github/workflows/build.yml
- .github/workflows/selenium_tests.yml
- tests/scripts/docker_check_tests.sh
Исправления https://github.com/moevm/document_insight_system/issues/594
> remove "-" from docker compose and add v4

- app/main/checks/report_checks/short_sections_check.py
Исправлен баг в проверке дл LR, связанный с заменой ранее списков на словари в конфигурации.
> fix LR config

- templater/app/config.ini
- templater/app/templater/static/js/main.js
- templater/app/templater/views/default.py
> fix: upload in Templater

- app/main/check_packs/pack_config.py
- app/main/checks/presentation_checks/__init__.py
- app/main/checks/presentation_checks/overview_in_tasks.py
Произведен поиск одного из ключевых слов (обзор, анализ) в задачах
> 556 overview in tasks

- app/main/check_packs/pack_config.py
- app/main/checks/presentation_checks/__init__.py
- app/main/checks/presentation_checks/task_tracker.py
- app/main/checks/report_checks/__init__.py
- app/main/checks/report_checks/task_tracker.py
Для того чтобы не пропускать задачи из серии "доделать, решить ...":
Был выполнен поиск задач. После их нахождения была создана проверка: начинается ли формулировка задачи с глагола.
> 557 task tracker

- templater/app/templater/routes.py
- templater/app/templater/templates/homepage.jinja2
- templater/app/templater/views/default.py
> Feat: add export created documents to cloud storage

- app/routes/upload.py
- templater/app/templater/routes.py
- templater/app/templater/templates/user_home.jinja2
- templater/app/templater/templates/user_templaters.jinja2
- templater/app/templater/views/default.py
> feat: add role definition via captcha
